baseURL = "https://stage.solarnetwork.org.nz/"
languageCode = "en-us"
title = "SolarNetwork Foundation"
theme = "snf-v1"
description = "SolarNetwork Foundation is a New Zealand registered charity focused on sustainability education and technology."
Paginate = 4
[Params]
  RSSLink = "/index.xml"
  author = "SolarNetwork" # add your company name
  github = "" # add your github profile name
  twitter = "" # add your twitter profile
  email = "info@solarnetwork.net"

[[menu.main]]
    name = "Home"
    weight = -100
    url = "/"

[[menu.main]]
    name = "What We Offer"
    weight = 100
    url = "/use-cases.html"

[[menu.main]]
    name = "What We’ve Done"
    weight = 200
    url = "/case-studies.html"

[[menu.main]]
    name = "Blog"
    weight = 300
    url = "/blog.html"

[[menu.main]]
    name = "About"
    weight = 400
    url = "/about.html"
