# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "SNF Kube"
license = "MIT"
licenselink = "https://github.com/jeblister/kube/master/LICENSE.md"
description = "SNF Kube is a customized version of the Kube theme, specific to SolarNetwork Foundation."
homepage = "https://solarnetwork.org.nz/"
tags = ["responsive", "kube", "documentation", "landing", "blog", "themes", "professional", "modern"]
features = ["Minimalism","Mobile-first Design",
  "Responsive Design",
  "Horizontal Rhythm",
  "Typography",
  "Google Analytics",
  "Disqus Commenting",
  "OpenGraph support",
  "Schema Structured Data",
  "Paginated Lists",
  "Reading Time",
  "Last Modified time",
  "Word Count",
  "Related Posts",
  "Block Templates",
  "Table of Contents",
  "SEO Site Verification"]
min_version = 0.19

[author]
  name = "msqr"
 
